title: "CP Archive"
description: "A categorized archive of CP problems with C++ and notes."
theme: just-the-docs
color_scheme: dark

baseurl: "" # keep this empty for GitHub Pages
url: "" # keep this empty for GitHub Pages

# Enable sidebar navigation
just_the_docs:
  logo: "/assets/logo.png"
  aux_links:
    "GitHub Repo":
      - "https://github.com/eyasir329/CP_Archive"

# Include files
include:
  - docs
  - .nojekyll

exclude:
  - convert.sh
  - .vscode
  - .github
