name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Prepare directories
        run: |
          cd docs
          mkdir -p _includes  # Create required directory

      - name: Generate content
        run: |
          cd docs
          chmod +x *.sh
          ./generate_readmes.sh
          ./update_stats.sh

      - name: Build site
        run: |
          cd docs
          bundle exec jekyll build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
