name: Deploy Jekyll site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Convert README.md to index.md
        run: ./convert.sh

      - name: Build site
        run: bundle exec jekyll build

      - name: Remove any nested .git directory from _site
        run: rm -rf ./_site/.git

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
